services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rpgf_user
      POSTGRES_PASSWORD: rpgf_password
      POSTGRES_DB: rpgf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rpgf_user
      POSTGRES_PASSWORD: rpgf_password
      POSTGRES_DB: rpgf_db_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpgf_user -d rpgf_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
