services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rpgf_user
      POSTGRES_PASSWORD: rpgf_password
      POSTGRES_DB: rpgf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
